### PR TITLE
aslt changes + grammar + testing

### LINKED ISSUE #44: testing of semantics output
to spot regressions in the optimisation/simplification passes, it will be useful to record and compare against expected output for some tricky instructions.

### LINKED ISSUE #45: adopt aslt grammar into this repository
by aslt, I mean the AST-like format for semantics used by basil and emitted by gtirb-semantics.

this format might eventually be used more widely and it will be useful to move the antlr grammar here for visibility and maintenance.

### PR DESCRIPTION
**Pull request by katrinafyi**
This PR will aim to address some inconveniences in the current aslt format (i.e. that from the AST's pp_raw methods). This should make the syntax more similar to a regular programming language (in particular, Python) and hence easier to parse with a variety of generic tools.

In the format itself,

- [x] Format integer literals with a prefix (e.g. 0x) and without wrapping in Expr\_Lit\*.
  - [ ] Possibly, strip non-digit characters when emitting.
- [x] Wrap identifiers (e.g. function identifiers) in double quotes, denoting them as strings.
- [x] Format else branches consistently (done in #51).
- [x] Investigate unnecessary parentheses.
- [x] Investigate use of space and semicolon delimited lists.

In the ANTLR grammar,

- [x] Update grammar with these changes.
- [x] Maintain a reference version of the grammar within this repository (#45).

In downstream projects,
- [x] Update downstream users to support the new format (https://github.com/UQ-PAC/bil-to-boogie-translator/pull/197)

### CODE REVIEW

**Comment by mmcloughlin** [comment]
In case it's of interest, I'm working on a Rust parser for ASLT (based on [pest](https://pest.rs/)). It's a work in progress but it parses a reasonable subset right now.

**Comment by katrinafyi** [comment]
@mmcloughlin, that is interesting! Do you have plans to make use of ASLp for a verification project?

**Comment by mmcloughlin** [comment]
> Do you have plans to make use of ASLp for a verification project?

Potentially, yes. I'm trying to see if it will work for our use case at the moment. The ASLT format is quite convenient.

The other thing we'll probably need is symbolic opcodes #52.

**Comment by mmcloughlin** [comment]
I've updated my Rust parser to support these new changes. All works fine.

**Comment by katrinafyi** [comment]
With the go-ahead of the Basil PR, this is scheduled for merge next Monday.

**Comment by katrinafyi** [comment]
@ncough Are the changes in [this diff](https://github.com/UQ-PAC/aslp/pull/53/commits/ecfa8467ed4cc1edf04a112365d97e570d036227) to be expected? It looks like some more CSE and some distributivity simplifications have been added?

**Comment by ncough** [comment]
Yeah, these should correspond to some simplifications over `mul_int` and `add_int` that were necessary to reduce bitvector slices down to a constant width. Given the resulting CSE mess, I may consider an alternative approach down the line. Nice to have this testing!

**Pull request merged**
