### PR TITLE
Floating Point Cleanup

### PR DESCRIPTION
**Pull request by ncough**
A series of improvements to improve the quality of floating point results. Mostly the conversion of enums to bit vectors and some cleanup around trivial case statements. Notably reduces coverage decompilation failures to only those instructions that refer to `FPToFixedJS`, due to its tuple return.

### CODE REVIEW

**Comment by katrinafyi** [comment]
A small question about the zext, from the example in #46. Is the extend needed if it's only going to be used by cvt_bits_uint? 

In general, I think the int to bits convention is to treat bit vectors as signed. Is this why?

**Comment by l-kent** [comment]
I'd expect in that example it's because the FPRounding type is an enum with 6 possible values so to represent it as a bitvector you need 3 bits, but in that example it's being converted from a 2-bit value which corresponds to one of the first four enum values.

**Comment by katrinafyi** [comment]
How interesting!

**Comment by ncough** [comment]
Yeah, the extend is due to the size of FPRounding type. The goal was to have consistent bit vector widths for arguments to `FPConvert`, even if they are via `cvt_bits_uint`, as a convenience to parsers if they chose to simply ignore the int conversion.

**Pull request merged**
